spring:
  application:
    name: orders-service
  datasource:
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    url: jdbc:mysql://localhost:3306/sec_kill?charset=utf-8mb4&useSSl=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka
server:
  port: 8083