spring:
  application:
    name: products-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sec_kill?charset=utf-8mb4&useSSl=false
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info,env