server:
  port: 8764
spring:
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://config-server-1:8761/eureka,http://config-server-2:8762/eureka,http://config-server-3:8763/eureka
