server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sec_kill
    username: root
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  application:
    name: storages-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
