eureka:
  instance:
    hostname: eureka-server-3
  client:
#    fetch-registry: true
#    register-with-eureka: true
    serviceUrl:
      defaultZone: http://config-server-1:8761/eureka/,http://config-server-2:8762/eureka/
server:
  port: 8761
spring:
  application:
    name: eureka-server