eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8764
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yngil/learn_spring_cloud
          username: spawnyngil@gmail.com
          password: yngil1009
          search-paths: '{application}'
          force-pull: true
          basedir: target/config
management:
  endpoints:
    web:
      exposure:
        include: health,info,env