eureka:
  instance:
    hostname: config-server
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8761
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yngil/learn_spring_cloud.git
          username: spawnyngil@gmail.com
          password: yngil1009
          search-paths: '{application}'