eureka:
  instance:
    hostname: config-server-2
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://config-server-1:8761/eureka/,http://config-server-3:8763/eureka/
server:
  port: 8761
spring:
  application:
    name: config-server