eureka:
  instance:
    hostname: config-server-1
  client:
#    fetch-registry: false
#    register-with-eureka: false
    serviceUrl:
      defaultZone: http://config-server-2:8762/eureka/,http://config-server-3:8763/eureka/
server:
  port: 8761
spring:
  application:
    name: config-server
